### ISSUE TITLE
Different Modules Gear Meshing

### ISSUE THREAD

**Issue by Archav** [DDeGonge/OS-ARM#10]
Can someone explain how the gears mesh? I'm currently working on my own harmonic drive with different gear ratio and am using this as a reference on how to go about printing it. 
Looking at the CAD files the ring gear and the flex spline have 70 and 68 teeth. When creating the gear in Inventors Spur Gear generator there is too much overlap in teeth to allow the flex spline to mesh. This design seems to be using two different gear modules to create more of a gap. has anyone encountered any issues with gear meshing or tips to know while printing?
Thanks in advance.

**Comment by DDeGonge** [comment]
The teeth were designed from scratch in my design, and the tooth was patterned 2 additional times over the same circumference. You may not be able to do this if you're using a script or add-on to generate the gear teeth. Additionally, the standard involute gear profile is probably not the optimal shape for this time of gearbox. So making teeth from scratch would give more room for improving efficiency and thus power output.
