### ISSUE TITLE
Upload SPT of the entire OS-ARM First Draft

### ISSUE THREAD

**Issue by cmagorian** [DDeGonge/OS-ARM#12]
Hey! 

Started using this at my own risk. I am mostly interested in just building out parts of the arm for 4DOF: Waist, Shoulder, Elbow and Wrist (1 DOF). Any way you could upload an STP of the First Draft assembly? The parts are in here, but I don't see the thing put together. Those of us using Onshape can't import the IAM files.

Thanks!
Chris

**Comment by DDeGonge** [comment]
Added under cad/FirstDraft/DraftAssembly.step
