### ISSUE TITLE
what program is required to edit the files?

### ISSUE THREAD

**Issue by bryanerayner** [DDeGonge/OS-ARM#5]
Novice question here - what program is required to edit these files? Are there any free / freemium programs which would allow access?

Not asking you to change the way you work - thanks so much for opening this up! But a simple programmer like myself with no CAD experience would just like to know how to cut his teeth.

Thanks!

**Comment by DDeGonge** [comment]
Autodesk Inventor is required to access the source files, though I have uploaded STEP files for the harmonic drive assembly and will for the full arm once it is in a stable place. STEP files can be opened and edited by most cad programs including some free ones, though editing features is not as easy as using Autodesk Inventor.
